spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/julyfire
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  #redis连接
  data:
    redis:
      host: 192.168.137.11
      port: 6379          # Redis 端口
      password:           # 密码（如有）
      database: 0         # 数据库索引
      lettuce:
        pool:
          max-active: 8   # 最大连接数
          max-idle: 8     # 最大空闲连接
          min-idle: 0     # 最小空闲连接
          max-wait: -1ms  # 最大阻塞等待时间
      timeout: 5000ms     # 连接超时时间

  #邮箱服务
  mail:
    host: smtp.qq.com
    port: 465
    username: 1716314512@qq.com
    password: mrixclmyrdaobdgj   # 这里填写刚刚获取的授权码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true